import Head from 'next/head'
// const inter:any = inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Practice Webapp - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className=" bg-slate-300"></div>
      </main>
    </>
  )
}

